name: trigger-workflow
on: pull_request

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: trilogy-group/action-npm-install-dependencies@v1
      - name: list
        run: npx ts-node list.ts
      - name: write
        run: npx ts-node write-json.ts
      - name: list
        run: npx ts-node list.ts
      - name: read
        run: npx ts-node read-json.ts
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: student
          path: student.json
  test:
    needs: analyze
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: trilogy-group/action-npm-install-dependencies@v1
      - name: list
        run: npx ts-node list.ts
      - name: Step 3 - Use the Download Artifact GitHub Action
        uses: actions/download-artifact@v2
        with: 
          name: student
          path: .
      - name: list
        run: npx ts-node list.ts
      - name: read
        run: npx ts-node read-json.ts
        
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: "**/package.json\n**/package-lock.json"
        run: ls -lah
