name: Undeploy integration test environment
on:
  workflow_run:
    workflows: ["trigger-workflow"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: step a1
        run: echo "github.event.workflow_run success"
      - name: step a2
        run: echo "${{github.event.workflow_run.conclusion}}"      
      - name: step a3
        run: echo "${{github.event.workflow_run.url}}"
      - name: step a5
        run: echo "${{github.event.workflow_run.check_suite}}"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: step b1
        run: echo "github.event.workflow_run failure"

